FOSWIKI_ROOT?=~/foswiki/core
SUBDIRS=\
  ui.knob \
  ui.slider \
  ngAnimate \
  ngAria \
  ngCookies \
  ngLoader \
  ngMessages \
  ngMocks \
  ngResource \
  ngRoute \
  ngSanitize \
  ngScenario \
  ngTouch \


-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include
